# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-26 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(default='default.jpg', upload_to='profiles/')),
                ('bio', tinymce.models.HTMLField(default='Tell Me Something', max_length=500)),
                ('website', url_or_relative_url_field.fields.URLOrRelativeURLField()),
                ('phone_number', models.CharField(default=12345678, max_length=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('image_landing', models.ImageField(upload_to='landing/')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=200)),
                ('link', url_or_relative_url_field.fields.URLOrRelativeURLField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
