# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-26 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default.png', upload_to='profiles/'),
        ),
    ]
