# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0003_projects_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='user',
            new_name='profile',
        ),
    ]
