# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0004_auto_20190527_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='profile',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trophy.Projects'),
        ),
    ]
