# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0006_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='content',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='design',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='usability',
            field=models.IntegerField(default=0),
        ),
    ]
