# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0008_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='user',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
    ]
